# yaml-language-server: $schema=values.schema.json
nameOverride: ""
fullnameOverride: ""

replicaCount: 1
labels: {}

imagePullSecrets: []
service:
  annotations: {}
  type: ClusterIP
  ports:
    - name: node-api
      port: 9010
      protocol: TCP
      targetPort: 9010
    - name: metrics
      port: 9091
      protocol: TCP
      targetPort: 9091

ingress:
  annotations: {}
  enabled: false
  host: example.com
  ingressClassName: "nginx"

configs:
  operator.yaml: |

    # this sets the logger level (true = info, false = debug)
    production: true

    # EigenLayer Slasher contract address

    # This is the address of the slasher which is deployed in the anvil saved state
    # The saved eigenlayer state is located in tests/anvil/eigenlayer-deployed-anvil-state.json
    avs_registry_coordinator_address: 0xE0315CCaF46A736BFAB173670CBcC97bE65Eb414
    operator_state_retriever_address: 0x12ddeDbB47340e6702529197cB593204A4aFa318

    # address which the aggregator listens on for operator signed messages
    aggregator_server_ip_port_address: https://us-central1-openoracle-de73b.cloudfunctions.net/backend_apis/api/report_result
    chain_name: eth

    # avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
    eigen_metrics_ip_port_address: 0.0.0.0:9091
    enable_metrics: true
    node_api_ip_port_address: 0.0.0.0:9010
    enable_node_api: true

    # we need to register the operator on startup when running the docker compose file
    # because unfortunately we cannot register the operator previously and save it in the anvil json file
    # This is because anvil only dumps the state, and not the receipt tree, so when we restart anvil with
    # the registered operator, it's blspubkey registering event with the compendium is not present anymore,
    # and so the aggregator can't find it.... very annoying
    register_operator_on_startup: true

register:
  enabled: true
  image:
    repository: gcr.io/openoracle-de73b/operator
    pullPolicy: Always
    tag: "latest"
  args:
    - --config=/app/config/operator.yaml
    - register-operator-with-avs

node:
  volumeMounts: []
  image:
    repository: gcr.io/openoracle-de73b/operator
    pullPolicy: Always
    tag: "latest"
  ports:
    - name: node-api
      containerPort: 9010
      protocol: TCP
    - name: metrics
      containerPort: 9091
      protocol: TCP
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi
  env: []
  args:
    - --config=/app/config/operator.yaml
    - start-operator
  readinessProbe:
    httpGet:
      path: /metrics
      port: 9091
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  # livenessProbe:
  #   httpGet:
  #     path: /metrics
  #     port: 9090
  #   initialDelaySeconds: 1200
  #   periodSeconds: 30
  #   timeoutSeconds: 3
  #   failureThreshold: 2
  #   successThreshold: 1

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  #
volumes: []
