---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eigenda
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  local:
    path: <EXISTING_FOLDER_TO_MOUNT>
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - <NAME_OF_A_NODE>
