# yaml-language-server: $schema=values.schema.json
nameOverride: ""
fullnameOverride: ""

replicaCount: 1
labels: {}

pvc:
  size: 10Gi
  storageClassName: default
  annotations: {}
  labels: {}

imagePullSecrets: []
service:
  annotations: {}
  type: ClusterIP
  ports:
    - name: node-api
      port: 9010
      protocol: TCP
      targetPort: 9010
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090

ingress:
  annotations: {}
  enabled: false
  host: example.com

configs:
  operator.yaml: |

    production: true

    operator_address: ""

    avs_registry_coordinator_address: 0x90c6d6f2A78d5Ce22AB8631Ddb142C03AC87De7a
    operator_state_retriever_address: 0xb7bb920538e038DFFEfcB55caBf713652ED2031F

    # If you have your own rpc you can switch to it
    eth_rpc_url: https://holesky.drpc.org
    eth_ws_url: wss://holesky.drpc.org

    ecdsa_private_key_store_path: /app/.operator-keys/operator.ecdsa.key.json
    bls_private_key_store_path: /app/.operator-keys/operator.bls.key.json

    db_path: /app/db

    aggregator_server_ip_port_address: "aggregator-holesky.avaprotocol.org:2206"

    eigen_metrics_ip_port_address: 0.0.0.0:9090
    enable_metrics: true
    node_api_ip_port_address: 0.0.0.0:9010
    enable_node_api: true

    enabled_features:
      event_trigger: false

register:
  enabled: true
  image:
    repository: avaprotocol/ap-avs
    pullPolicy: Always
    tag: ""
  command:
    - /ava
  args:
    - register
    - --config=/app/config/operator.yaml

node:
  volumeMounts: []
  image:
    repository: avaprotocol/ap-avs
    pullPolicy: Always
    tag: ""
  ports:
    - name: node-api
      containerPort: 9010
      protocol: TCP
    - name: metrics
      containerPort: 9090
      protocol: TCP
  # -- Resources configuration
  # @schema
  # additionalProperties: true
  # @schema
  resources:
    {}
    # limits:
    #   cpu: 4
    #   memory: 16Gi
    # requests:
    #   cpu: 2
    #   memory: 8Gi
  env: []
  command:
    - /ava
  args:
    - operator
    - --config=/app/config/operator.yaml
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: 9090
  #   initialDelaySeconds: 30
  #   periodSeconds: 10
  #   timeoutSeconds: 3
  #   failureThreshold: 3
  #   successThreshold: 1
  # livenessProbe:
  #   httpGet:
  #     path: /metrics
  #     port: 9090
  #   initialDelaySeconds: 1200
  #   periodSeconds: 30
  #   timeoutSeconds: 3
  #   failureThreshold: 2
  #   successThreshold: 1

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  #
volumes: []
