name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
      - name: Debug Branch Information
        run: |
          echo "Default Branch: ${{ github.event.repository.default_branch }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Debug env
        run: |
          cat /opt/hostedtoolcache/ct/3.12.0/amd64/etc
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          ct list-changed --target-branch ${{ github.event.repository.default_branch }}
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
